remote_theme: pdmosses/just-the-docs@nav-fix

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-seo-tag

title: Francisco Knebel
logo: https://avatars.githubusercontent.com/u/10299622?v=4
url: "https://franciscoknebel.com"
permalink: pretty

###########
# JUST THE DOCS CONFIGURATION
# https://pmarsceill.github.io/just-the-docs/docs/configuration
###########

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

ga_tracking: G-80D0XB0GGG
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

color_scheme: light

enable_copy_code_button: true
heading_anchors: true


aux_links:
  "GitHub":
    - "//github.com/FranciscoKnebel"

collections:
  projects:
    permalink: "/:collection/:path/"
    output: true
  experiences:
    permalink: "/:collection/:path/"
    output: true
  academic:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    projects:
      name: Projects
    experiences:
      name: Experiences
    experiences:
      name: Academic

back_to_top: true
back_to_top_text: "Back to top"
